### ISSUE TITLE
ngram request triggered three times

### ISSUE THREAD

**Issue by BeritJanssen** [CentreForDigitalHumanities/I-analyzer#1268]
When trying to see the "neighbouring words" graph and opening the Network inspector, this shows the ngram request to be triggered three times. The call stack shows the following:
- first trigger `onChanges`. We listen to the corpus and queryModel input here. The initial state of the data does (but should not) trigger `loadGraph`.
- second trigger: `setStateFromParams`
- third trigger: `setStateFromParams`
One of the two triggers is likely caused by the updates from the `visualization.component` (see also #1374).

**Comment by lukavdplas** [comment]
This can be addressed by implementing #1468. But if an easy fix is possible, that may be preferable.
