### ISSUE TITLE
Deduplicate corpora when user has multiple roles

### ISSUE THREAD

**Issue by BeritJanssen** [CentreForDigitalHumanities/I-analyzer#1672]
### What went wrong?

Right now, a corpus may appear multiple times in the list if a user has multiple roles.

### What did you expect to happen?

Each corpus should only appear once.

### Screenshot
<img width="1089" alt="Screenshot 2024-10-02 at 14 25 39" src="https://github.com/user-attachments/assets/d79bad14-ef76-448c-8018-8c854665d3ea">

### Where did you find the bug?

- [X] https://ianalyzer.hum.uu.nl
- [ ] https://peopleandparliament.hum.uu.nl
- [ ] https://peace.sites.uu.nl
- [ ] a server hosted elsewhere (i.e. not by the research software lab)
- [ ] a local server

### Steps to reproduce

Log in with a user that has multiple roles.

**Comment by lukavdplas** [comment]
closed by #1702
